CREATE TABLE users (
    username VARCHAR(30) PRIMARY KEY,
    password CHAR NOT NULL,
    email VARCHAR(50) NOT NULL,
    full_name VARCHAR(70) NOT NULL,
    phone_number VARCHAR(15) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    token CHAR

);